nombreA = 8
nombreB = 4

resultat1 = ...
print("8 - 4 =", resultat1)

resultat2 = ...
print("A * B =", resultat2)

resultat3 = ...
resultat4 = ...
print("A divisé par B donne un quotient de", resultat3, "et un reste de", resultat4)
