@startuml classDiagramExemple
skinparam classAttributeIconSize 0

abstract class Dragon {
    - int power
    # int getPower()
    # void setPower(int power)
}

class Dragonite {
    - int pokemonNumber
    + int getPokemonNumber()
    + Dragonite(int power, int pokemonNumber)
}

Dragon <|-- Dragonite

note left of Dragonite
    This is a note
    on two lines
end note

@enduml